version: '3.8'

services:
  # binlog được bật là on theo mặc định mysql. Thích thì kiểm tra
  # SHOW VARIABLES LIKE 'log_bin';
  # Server_id là 1 do không có cơ chế nhân bản thành cụm mysql.
  db-app:
    image: mysql:8.0
    hostname: db-app
    container_name: db-app
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: raw
      MYSQL_USER: vohoang
      MYSQL_PASSWORD: 12345678
      MYSQL_SSL: 'false'
    ports:
      - "3307:3306"
    volumes:
      - db_app:/var/lib/mysql
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bigdata

  db-report:
    image: mysql:8.0
    hostname: db-report
    container_name: db-report
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mart
      MYSQL_USER: vohoang
      MYSQL_PASSWORD: 12345678
      MYSQL_SSL: 'false'
    ports:
      - "3308:3306"
    volumes:
      - db_report:/var/lib/mysql
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bigdata

  # db-cache:
  #   image: redis:latest
  #   hostname: db-cache
  #   container_name: db-cache
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - db_cache:/data
  #     - ./config/db/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   networks:
  #     - bigdata

  # minio:
  #   image: quay.io/minio/minio:latest
  #   hostname: minio
  #   container_name: minio
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=password
  #     - MINIO_REGION_NAME=us-east-1
  #   command: server --console-address ":9001" /data
  #   ports:
  #     - 9001:9001
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   volumes:
  #     - datalake:/data
  #   networks:
  #     - bigdata

volumes:
  # db_cache:
  db_app:
  db_report:
  # datalake:

networks:
  bigdata:
    external: true